#!/bin/bash

read -rp 'wipe all configs and plugins? yes to continue: ' confirm

if [ "${confirm}" = "yes" ]
then
	rm -rf ~/.config/nvim
	rm -rf ~/.local/nvim
	rm -rf ~/.local/state/nvim
        git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
	cp init.lua ~/.config/nvim/init.lua
	cp plugins/* ~/.config/nvim/lua/custom/plugins/

	mkdir ~/.config/nvim/lua/custom/include
	cp include/* ~/.config/nvim/lua/custom/include/


fi




# ## allow initialization
# RUN timeout 60 nvim --headless || true
#
# RUN nvim --headless -c 'MasonInstall ansible-language-server'  -c qa
# RUN nvim --headless -c 'MasonInstall ansible-lint'  -c qa
# RUN nvim --headless -c 'MasonInstall bash-language-server'  -c qa
# RUN nvim --headless -c 'MasonInstall shellcheck'  -c qa
# # RUN nvim --headless -c 'MasonInstall basedpyright'  -c qa
#
#
#
# RUN cd /home/nvim
#
# # CMD [ "/bin/bash" ]
